In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
name_data = "data.xlsx"
name_label = "y.xlsx"

In [21]:
data = pd.read_excel(name_data)
y = pd.read_excel(name_label)

In [22]:
data

AGE_YEARS  WEEKS_PREGNANCY  HEALTH_PROBLEM_CAT  DESIRED_PREG_CAT  \
0           27               25                   9                 1   
1           17               24                  10                 2   
2           25               37                   9                 1   
3           24               26                   8                 2   
4           30               25                  13                 2   
..         ...              ...                 ...               ...   
102         30               28                   9                 2   
103         30               33                   9                 1   
104         30               15                  11                 1   
105         36               32                  10                 2   
106         20               21                   9                 1   

     EMPLOYED_CAT  INSTRUCTION_CAT  INCOME_CAT  MARITAL_STATUS_CAT  MENTAL_CAT  
0               1                4           2                   2           2  
1               2                3           5                   2           2  
2               1                3           6                   2           4  
3               2                3           1                   3           2  
4               2                3           1                   1           1  
..            ...              ...         ...                 ...         ...  
102             2                6           1                   4           4  
103             1                5           5                   4           4  
104             2                6           3                   4           4  
105             1                4           1                   4           4  
106             1                6           5                   4           4  

[107 rows x 9 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size = 0.15)

In [24]:
scaler = StandardScaler()  
scaler.fit(X_train)
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)

In [25]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 4), max_iter=3000)  
mlp.fit(X_train, y_train.values.ravel())
predictions = mlp.predict(X_test)
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions, digits=4))

[[5 4]
 [2 6]]
              precision    recall  f1-score   support

           1     0.7143    0.5556    0.6250         9
           2     0.6000    0.7500    0.6667         8

    accuracy                         0.6471        17
   macro avg     0.6571    0.6528    0.6458        17
weighted avg     0.6605    0.6471    0.6446        17



In [ ]:
probabilities = mlp.predict_proba(X_test)

In [ ]:
probabilities

In [ ]:
y_train

In [ ]:
y_array = y_train[["DEPRESSION"]].to_numpy()
y_array

In [26]:
from sklearn.svm import SVC
from sklite import LazyExport

In [9]:
clf = SVC(gamma='auto', kernel='linear', probability=True)
clf.fit(X_train, y_train.values.ravel())

SVC(gamma='auto', kernel='linear', probability=True)

In [10]:
predictions = clf.predict(X_test)
print(confusion_matrix(y_test.values.ravel(),predictions))  
print(classification_report(y_test.values.ravel(),predictions, digits=4))

[[2 5]
 [2 8]]
              precision    recall  f1-score   support

           1     0.5000    0.2857    0.3636         7
           2     0.6154    0.8000    0.6957        10

    accuracy                         0.5882        17
   macro avg     0.5577    0.5429    0.5296        17
weighted avg     0.5679    0.5882    0.5589        17



In [ ]:
import pickle
filename = 'model.sav'
pickle.dump(clf, open(filename, 'wb'))

In [28]:
lazy = LazyExport(mlp)
lazy.save('mlp.json')

In [ ]:
filename = 'model.sav'
loaded_model = pickle.load(open(filename, 'rb'))

In [ ]:
loaded_model.predict_proba(X_test)

In [ ]:
X_test.values.ravel()[0:9]

In [ ]:
y_test.values.ravel()[0]

In [19]:
from sklearn.model_selection import cross_val_score
mlp2 = MLPClassifier(hidden_layer_sizes=(10, 4), max_iter=3000)  
scores = cross_val_score(mlp2, data, y.values.ravel(), cv=5)
print(scores)
scores.mean()

[0.63636364 0.54545455 0.66666667 0.76190476 0.61904762]


0.6458874458874458

In [30]:
mlp.intercepts_

[array([ 0.19399675, -0.73360941, -0.13317566,  0.48681685,  0.40937437,
         1.15283897,  0.43326919, -0.36254367,  0.66155625,  0.20103892]),
 array([ 0.51804601, -0.34049591,  0.82176271,  0.80884404]),
 array([-1.32035162])]